version: '3.8'
services:
    bot:
        container_name: aiogram-and-sqlalchemy-demo-bot
        image: registry.gitlab.com/groosha/aiogram-and-sqlalchemy-demo:latest
        restart: always
        environment:
            - BOT_TOKEN
            - DB_HOST
            - DB_USER
            - DB_PASS
            - DB_NAME
        depends_on:
            - db
    db:
        container_name: aiogram-and-sqlalchemy-demo-db
        image: postgres:12-alpine
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB_NAME}
        volumes:
            - "postgres_data:/var/lib/postgresql/data"
    # This is optional, not necessary
    pgadmin:
        container_name: aiogram-and-sqlalchemy-demo-pgadmin
        image: dpage/pgadmin4
        restart: always
        environment:
            # These variables could be also moved to .env file, but I don't care
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: 4RIDDLE7MISCHANCE4opaqueness1
        ports:
            - "5050:80"
        volumes: 
            - "pgadmin_data:/var/lib/pgadmin"

volumes:
    postgres_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './postgres_data'
    pgadmin_data:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: './pgadmin_data'
